### ISSUE TITLE
Error in kafka spout in bro topology

### ISSUE THREAD

**Issue by mandreoni** [OpenSOC/opensoc-vagrant#11]
I'm having this error during the execution of fab vagrant quickstart in kafka spout:

java.lang.NoSuchMethodError: org.apache.zookeeper.ZooKeeper.<init>(Ljava/lang/String;ILorg/apache/zookeeper/Watcher;Z)V at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29) at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:169) at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55) at org.apache.curator.ConnectionState.reset(ConnectionState.java:219) at org.apache.curator.ConnectionState.start(ConnectionState.java:103) at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:188) at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:234) at storm.kafka.ZkState.<init>(ZkState.java:62) at storm.kafka.KafkaSpout.open(KafkaSpout.java:85) at backtype.storm.daemon.executor$fn__4654$fn__4669.invoke(executor.clj:522) at backtype.storm.util$async_loop$fn__458.invoke(util.clj:461) at clojure.lang.AFn.run(AFn.java:24) at java.lang.Thread.run(Unknown Source)

**Comment by BlondAngel** [comment]
I have encountered this too.

**Comment by mandreoni** [comment]
I think I've solved this issue.
The problem is the different version between opensoc-streaming and opensoc-vagrant.
Basically I updated the opensoc-streaming pom.xml with the same version that opensoc-vagrant\common.sh. Even I created  "<global_hbase_version>0.98.13-hadoop2</global_hbase_version>", for flume and zookeeper as well, in opensoc-streaming/pom.xml.
Then I updated all pom.xml in the different opensoc-streaming folders. 
for ex: in opensoc-streaming/OpenSOC-Pcap_Service/pom.xml line 13, I updated with                 <flume.version>${global_flume_version}</flume.version> created in opensoc-streaming/pom.xml
then I did: fab vagrant quickstart, and the topologies are running in the storm-ui.
The problem now is that topologies are not gathering any data.
Could you check this @BlondAngel ?
