### ISSUE TITLE
zookeper error running fab vagrant quickstart in data branch

### ISSUE THREAD

**Issue by charlesporter** [OpenSOC/opensoc-vagrant#9]
(error occurs even after locally addressing issues #5 and #6)

[node1] out: 2015-07-23 06:29:22,811 ERROR [main] zookeeper.ZooKeeperWatcher: hconnection-0x1c5650570x0, quorum=node3:2181,node2:2181,node4:2181, baseZNode=/hbase-unsecure Received unexpected KeeperException, re-throwing exception
[node1] out: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase-unsecure
[node1] out:    at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
[node1] out:    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
[node1] out:    at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
[node1] out:    at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
[node1] out:    at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
[node1] out:    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:925)
[node1] out:    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:599)
[node1] out:    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1626)
[node1] out:    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1672)
[node1] out:    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1726)
[node1] out:    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1933)
[node1] out:    at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3389)
[node1] out:    at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
[node1] out:    at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
[node1] out:    at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3416)
[node1] out:    at org.apache.hadoop.hbase.client.HBaseAdmin.createTableAsync(HBaseAdmin.java:632)
[node1] out:    at org.apache.hadoop.hbase.client.HBaseAdmin.createTable(HBaseAdmin.java:523)
[node1] out:    at org.apache.hadoop.hbase.client.HBaseAdmin.createTable(HBaseAdmin.java:457)
[node1] out:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[node1] out:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[node1] out:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[node1] out:    at java.lang.reflect.Method.invoke(Unknown Source)
[node1] out:    at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:450)
[node1] out:    at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:311)
[node1] out:    at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:59)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
[node1] out:    at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.IfNode.interpret(IfNode.java:117)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:233)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:215)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
[node1] out:    at org.jruby.ast.CallSpecialArgNode.interpret(CallSpecialArgNode.java:69)
[node1] out:    at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:111)
[node1] out:    at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
[node1] out:    at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:295)
[node1] out:    at org.jruby.runtime.InterpretedBlock.yieldSpecific(InterpretedBlock.java:229)
[node1] out:    at org.jruby.runtime.Block.yieldSpecific(Block.java:99)
[node1] out:    at org.jruby.ast.ZYieldNode.interpret(ZYieldNode.java:25)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:191)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:144)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:153)
[node1] out:    at org.jruby.ast.FCallNoArgBlockNode.interpret(FCallNoArgBlockNode.java:32)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:255)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:223)
[node1] out:    at org.jruby.RubyClass.finvoke(RubyClass.java:611)
[node1] out:    at org.jruby.RubyBasicObject.send(RubyBasicObject.java:2787)
[node1] out:    at org.jruby.RubyKernel.send(RubyKernel.java:2113)
[node1] out:    at org.jruby.RubyKernel$s$send.call(RubyKernel$s$send.gen:65535)
[node1] out:    at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrThreeOrNBlock.call(JavaMethod.java:300)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:352)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:237)
[node1] out:    at org.jruby.ast.FCallSpecialArgNode.interpret(FCallSpecialArgNode.java:43)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:111)
[node1] out:    at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
[node1] out:    at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:295)
[node1] out:    at org.jruby.runtime.InterpretedBlock.yieldSpecific(InterpretedBlock.java:229)
[node1] out:    at org.jruby.runtime.Block.yieldSpecific(Block.java:99)
[node1] out:    at org.jruby.ast.ZYieldNode.interpret(ZYieldNode.java:25)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
[node1] out:    at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
[node1] out:    at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:255)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:223)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:342)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:212)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:221)
[node1] out:    at org.jruby.ast.FCallSpecialArgBlockNode.interpret(FCallSpecialArgBlockNode.java:38)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
[node1] out:    at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
[node1] out:    at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:120)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:134)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:174)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:282)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:71)
[node1] out:    at org.jruby.ast.CallSpecialArgNode.interpret(CallSpecialArgNode.java:73)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:120)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:134)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:174)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:282)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:71)
[node1] out:    at org.jruby.ast.FCallSpecialArgNode.interpret(FCallSpecialArgNode.java:45)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:276)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:231)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:352)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:237)
[node1] out:    at org.jruby.ast.CallSpecialArgNode.interpret(CallSpecialArgNode.java:71)
[node1] out:    at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
[node1] out:    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:233)
[node1] out:    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:215)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
[node1] out:    at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
[node1] out:    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
[node1] out:    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
[node1] out:    at org.jruby.ast.RootNode.interpret(RootNode.java:129)
[node1] out:    at org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:119)
[node1] out:    at org.jruby.Ruby.runInterpreter(Ruby.java:724)
[node1] out:    at org.jruby.Ruby.loadFile(Ruby.java:2489)
[node1] out:    at org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:66)
[node1] out:    at org.jruby.runtime.load.LoadService.load(LoadService.java:270)
[node1] out:    at org.jruby.RubyKernel.loadCommon(RubyKernel.java:1105)
[node1] out:    at org.jruby.RubyKernel.load(RubyKernel.java:1087)
[node1] out:    at org.jruby.RubyKernel$s$0$1$load.call(RubyKernel$s$0$1$load.gen:65535)
[node1] out:    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:211)
[node1] out:    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:207)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
[node1] out:    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
[node1] out:    at opt.hbase.bin.$_dot_dot_.bin.hirb.**file**(/opt/hbase/bin/../bin/hirb.rb:177)
[node1] out:    at opt.hbase.bin.$_dot_dot_.bin.hirb.load(/opt/hbase/bin/../bin/hirb.rb)
[node1] out:    at org.jruby.Ruby.runScript(Ruby.java:697)
[node1] out:    at org.jruby.Ruby.runScript(Ruby.java:690)
[node1] out:    at org.jruby.Ruby.runNormally(Ruby.java:597)
[node1] out:    at org.jruby.Ruby.runFromMain(Ruby.java:446)
[node1] out:    at org.jruby.Main.doRunFromMain(Main.java:369)
[node1] out:    at org.jruby.Main.internalRun(Main.java:258)
[node1] out:    at org.jruby.Main.run(Main.java:224)
[node1] out:    at org.jruby.Main.run(Main.java:208)
[node1] out:    at org.jruby.Main.main(Main.java:188)
[node1] out: 2015-07-23 06:29:22,814 ERROR [main] client.HConnectionManager$HConnectionImplementation: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase-unsecure
[node1] out: 
Stopped.

**Comment by tpiscitell** [comment]
where any of these machines halted? (`vagrant halt`) between inception and running `fab vagrant quickstart`?

**Comment by charlesporter** [comment]
I have done it both ways with same result (with vagrant up in between)

**Comment by charlesporter** [comment]
that is, tried both with and without 'halt' and 'up' between provision and
quickstart

**Comment by BlondAngel** [comment]
I fixed this in my fork.  Waiting for authors to approve my pull into this.
